// =============================================================================
// USES
// =============================================================================

// -----------------------------------------------------------------------------
use crate::Cli;
use crate::common::UnicodeVersion;
use anyhow::{Result, anyhow};
use std::fs::File;
use std::io::Cursor;
use std::io::Write;
use std::path::Path;
use std::process::{Command, Output};
use version::Version;
use zip::ZipArchive;

// =============================================================================
// HELPERS
// =============================================================================

// -----------------------------------------------------------------------------
fn generate_file_from_content(path: &Path, version: &Version, contents: &str) -> Result<()> {
    let mut file = std::fs::File::create(path)?;
    writeln!(
        file,
        r#"// =============================================================================
//                          DO NOT HAND EDIT THIS FILE!
// -----------------------------------------------------------------------------
// This file was generated by `typed-ident-generator update-tables`. Please use
// that utility to update this file (see generator/README.md for more info.)
// -----------------------------------------------------------------------------
//                               Unicode {}.{}.{}
// ============================================================================="#,
        version.major, version.minor, version.patch
    )?;

    let mut linebreak = true;
    for line in contents.lines() {
        if line.trim().is_empty() || line.starts_with("//") {
            linebreak = true;
            continue;
        }
        if linebreak {
            writeln!(file)?;
            writeln!(
                file,
                "// -----------------------------------------------------------------------------"
            )?;
        }
        writeln!(file, "{line}")?;
        linebreak = false;
    }

    Ok(())
}

// -----------------------------------------------------------------------------
fn generate_file_from_output(path: &Path, version: &Version, output: Output) -> Result<()> {
    if !output.status.success() {
        eprintln!("{}", String::from_utf8_lossy(output.stderr.as_slice()));
        return Err(anyhow!(
            "process failed with status code: {}",
            output.status
        ));
    }

    generate_file_from_content(path, version, &String::from_utf8(output.stdout)?)
}

// =============================================================================
// COMMAND
// =============================================================================

// -----------------------------------------------------------------------------
pub fn update_tables(cli: &Cli) -> Result<()> {
    let unicode = match &cli.unicode_version {
        Some(version) => UnicodeVersion::from_str(version.as_str())?,
        None => UnicodeVersion::latest()?,
    };
    println!("Selecting Unicode version {}", &unicode.version);

    // Select the source directory, and ensure it's pointing at something that
    // looks like the `typed-ident` source root.
    let generator_tables_src = cli.srcdirs()?.generator_tables;

    let ucd_tempdir = generator_tables_src.join("ucd");
    if !cli.skip_download || !ucd_tempdir.exists() {
        if ucd_tempdir.exists() {
            println!("Cleaning up old UCD data directory {ucd_tempdir:?}");
            std::fs::remove_dir_all(&ucd_tempdir)?;
        }
        std::fs::create_dir_all(&ucd_tempdir)?;

        // Get all of the UCD data...
        let ucd_zip = unicode.url.join("ucd/UCD.zip")?;
        println!(
            "Downloading data for Unicode version {} ({ucd_zip})",
            &unicode.version
        );
        let archive_bytes = reqwest::blocking::get(ucd_zip)?.bytes()?;

        let reader = Cursor::new(archive_bytes);
        let mut archive = ZipArchive::new(reader)?;
        for index in 0..archive.len() {
            let mut entry = archive.by_index(index)?;

            let entry_path = match entry.enclosed_name() {
                Some(path) => path.to_owned(),
                None => {
                    eprintln!("Skipping unsafe path: {}", entry.name());
                    continue;
                }
            };

            let destination = ucd_tempdir.join(&entry_path);

            if entry.is_dir() {
                std::fs::create_dir_all(&destination)?;
                continue;
            }

            if let Some(parent) = destination.parent() {
                std::fs::create_dir_all(parent)?;
            }

            let mut output_file = File::create(&destination)?;
            std::io::copy(&mut entry, &mut output_file)?;
        }
    }

    println!("Updating unicode tables to {}", &unicode.version);

    // Generate tables
    generate_file_from_output(
        &generator_tables_src.join("script.rs"),
        &unicode.version,
        Command::new("ucd-generate")
            .arg("script")
            .arg(&ucd_tempdir)
            .arg("--include")
            .arg("Greek")
            .output()?,
    )?;
    generate_file_from_output(
        &generator_tables_src.join("general_category.rs"),
        &unicode.version,
        Command::new("ucd-generate")
            .arg("general-category")
            .arg(&ucd_tempdir)
            .arg("--include")
            .arg("EnclosingMark,NonspacingMark,SpacingMark,Titlecase_Letter")
            .output()?,
    )?;
    generate_file_from_content(
        &generator_tables_src.join("version.rs"),
        &unicode.version,
        &format!(
            "pub const UNICODE_VERSION: (u32, u32, u32) = ({}, {}, {});",
            unicode.version.major, unicode.version.minor, unicode.version.patch,
        ),
    )?;

    // Clean up after ourselves.
    if !cli.skip_cleanup {
        println!("Cleaning up tempdir {ucd_tempdir:?}");
        std::fs::remove_dir_all(ucd_tempdir)?;
    }

    Ok(())
}
