//! Presets to set commonly used identifier formats.
//!
//! This module contains multiple submodules, which allows you to narrow-in on a
//! desired configuration.
//!
//! * [`ascii`] - Identifier which use the [`Ascii`](crate::syntax::profile::Ascii)
//!   profile and the [`Standard`] boundary implementation with [`Default`] options
//! * [`strict`] - Identifier which use the [`Strict`](crate::syntax::profile::Strict)
//!   profile and the [`Standard`] boundary implementation with [`Default`] options
//! * [`unicode`] - Identifier which use the [`Unicode`](crate::syntax::profile::Unicode)
//!   profile and the [`Standard`] boundary implementation with [`Default`] options
//! * [`generic`] - Configurations which are generic over their boundary and character
//!   profile (but have predefined delimiters and case profiles)
//!
//! [`Options`]: crate::syntax::boundary::Options
//! [`Default`]: crate::syntax::boundary::options::Default
//! [`Standard`]: crate::syntax::boundary::Standard
//!
#![doc = include_str!("README.md")]
//!
//! [`CamelIdent`]: generic::CamelIdent
//! [`CasedCamelIdent`]: generic::CasedCamelIdent
//! [`LowerCamelIdent`]: generic::LowerCamelIdent
//! [`UpperCamelIdent`]: generic::UpperCamelIdent
//! [`HybridIdent`]: generic::HybridIdent
//! [`CasedHybridIdent`]: generic::CasedHybridIdent
//! [`LowerHybridIdent`]: generic::LowerHybridIdent
//! [`UpperHybridIdent`]: generic::UpperHybridIdent
//! [`KebabIdent`]: generic::KebabIdent
//! [`CasedKebabIdent`]: generic::CasedKebabIdent
//! [`LowerKebabIdent`]: generic::LowerKebabIdent
//! [`UpperKebabIdent`]: generic::UpperKebabIdent
//! [`SnakeIdent`]: generic::SnakeIdent
//! [`CasedSnakeIdent`]: generic::CasedSnakeIdent
//! [`LowerSnakeIdent`]: generic::LowerSnakeIdent
//! [`UpperSnakeIdent`]: generic::UpperSnakeIdent

// =============================================================================
// MACRO
// =============================================================================

// -----------------------------------------------------------------------------
macro_rules! impl_type_aliases {
    (
        names={
            chunk=$chunk:ident,
            fragment=$fragment:ident,
            fragment_buf=$fragment_buf:ident,
            ident=$ident:ident,
            module=$module:ident,
            segment=$segment:ident,
        },
        options=$options:ident,
        case=$case:ident,
        delimiter=$delimiter:ident,
        docs=$docs:expr,
    ) => {
        #[allow(missing_docs)]
        #[doc = concat!("Types relating to [`", stringify!($ident) ,"`].")]
        pub mod $module {
            #[doc = concat!("The chunk type for [`", stringify!($ident) ,"`].")]
            pub type $chunk<P, O = crate::syntax::boundary::options::$options> = crate::core::Chunk<
                crate::syntax::boundary::Standard<O>,
                crate::syntax::delimiter::$delimiter,
                crate::syntax::profile::case::$case<P>,
            >;

            #[doc = concat!("The fragment type for [`", stringify!($ident) ,"`].")]
            pub type $fragment<P, O = crate::syntax::boundary::options::$options> = crate::core::Fragment<
                crate::syntax::boundary::Standard<O>,
                crate::syntax::delimiter::$delimiter,
                crate::syntax::profile::case::$case<P>,
            >;

            #[cfg(feature = "alloc")]
            #[doc = concat!("The fragment buffer type for [`", stringify!($ident) ,"`].")]
            pub type $fragment_buf<P, O = crate::syntax::boundary::options::$options> = crate::alloc::FragmentBuf<
                crate::syntax::boundary::Standard<O>,
                crate::syntax::delimiter::$delimiter,
                crate::syntax::profile::case::$case<P>,
            >;

            #[doc = $docs]
            pub type $ident<P, O = crate::syntax::boundary::options::$options> = crate::core::Ident<
                crate::syntax::boundary::Standard<O>,
                crate::syntax::delimiter::$delimiter,
                crate::syntax::profile::case::$case<P>,
            >;

            #[doc = concat!("The segment type for [`", stringify!($ident) ,"`].")]
            pub type $segment<'a, P, O = crate::syntax::boundary::options::$options> = crate::core::Segment<
                crate::syntax::delimiter::$delimiter,
                &'a crate::core::Chunk<
                    crate::syntax::boundary::Standard<O>,
                    crate::syntax::delimiter::$delimiter,
                    crate::syntax::profile::case::$case<P>
                >,
            >;
        }
        #[doc(inline)]
        pub use $module::$ident;
    };
    (
        profile=$profile:ident,
        names={
            chunk=$chunk:ident,
            fragment=$fragment:ident,
            fragment_buf=$fragment_buf:ident,
            ident=$ident:ident,
            module=$module:ident,
            segment=$segment:ident,
        },
        options=$options:ident,
        case=$case:ident,
        delimiter=$delimiter:ident,
        docs=$docs:expr,
    ) => {
        #[allow(missing_docs)]
        #[doc = concat!("Types relating to [`", stringify!($ident) ,"`].")]
        pub mod $module {
            #[doc = concat!("The chunk type for [`", stringify!($ident) ,"`].")]
            pub type $chunk = crate::core::Chunk<
                crate::syntax::boundary::Standard<crate::syntax::boundary::options::$options>,
                crate::syntax::delimiter::$delimiter,
                crate::syntax::profile::case::$case<crate::syntax::profile::$profile>,
            >;

            #[doc = concat!("The fragment type for [`", stringify!($ident) ,"`].")]
            pub type $fragment = crate::core::Fragment<
                crate::syntax::boundary::Standard<crate::syntax::boundary::options::$options>,
                crate::syntax::delimiter::$delimiter,
                crate::syntax::profile::case::$case<crate::syntax::profile::$profile>,
            >;

            #[cfg(feature = "alloc")]
            #[doc = concat!("The fragment buffer type for [`", stringify!($ident) ,"`].")]
            pub type $fragment_buf = crate::alloc::FragmentBuf<
                crate::syntax::boundary::Standard<crate::syntax::boundary::options::$options>,
                crate::syntax::delimiter::$delimiter,
                crate::syntax::profile::case::$case<crate::syntax::profile::$profile>,
            >;

            #[doc = $docs]
            pub type $ident = crate::core::Ident<
                crate::syntax::boundary::Standard<crate::syntax::boundary::options::$options>,
                crate::syntax::delimiter::$delimiter,
                crate::syntax::profile::case::$case<crate::syntax::profile::$profile>,
            >;

            #[doc = concat!("The segment type for [`", stringify!($ident) ,"`].")]
            pub type $segment<'a> = crate::core::Segment<
                crate::syntax::delimiter::$delimiter,
                &'a crate::core::Chunk<
                    crate::syntax::boundary::Standard<crate::syntax::boundary::options::$options>,
                    crate::syntax::delimiter::$delimiter,
                    crate::syntax::profile::case::$case<crate::syntax::profile::$profile>,
                >,
            >;
        }
        #[doc(inline)]
        pub use $module::$ident;
    };
    (
        $($tt:tt)*
    ) => {
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=CamelChunk,
                fragment=CamelFragment,
                fragment_buf=CamelFragmentBuf,
                ident=CamelIdent,
                module=camel,
                segment=CamelSegment,
            },
            options=Default,
            case=Mixed,
            delimiter=LowLine,
            docs=concat!(
                "A camel-cased identifier, but without specific requirements ",
                "on the casing.",
                "\n\n",
                "Camel-cased identifiers are identifiers which usually prefer ",
                "to separate words within a chunk by case convention (lower-to-upper ",
                "or upper-to-lower).",
                "\n\n",
                "If casing alone is not enough to separate words, then an explicit ",
                "delimiter (`_`) may be used.",
                "\n\n",
                "Use this type when you want to be as permissive as possible, ",
                "while still allowing for detection of something vaguely camel-cased.",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "Within the same format of identifiers (camel-cased), this is the ",
                "most permissive form. However, there are more restrictive forms.",
                "\n\n",
                "* `CamelIdent` *(This Identifier)* \n",
                "* [`CasedCamelIdent`] *(More Restrictive)* \n",
                "* [`LowerCamelIdent`] *(More Restrictive)* \n",
                "* [`UpperCamelIdent`] *(More Restrictive)* \n",
                "\n\n",
                "If you need something more general that may match this or ",
                "several other formats, you could consider the [`HybridIdent`] ",
                "identifier formats.",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`CasedCamelIdent`]: super::CasedCamelIdent\n",
                "[`LowerCamelIdent`]: super::LowerCamelIdent\n",
                "[`UpperCamelIdent`]: super::UpperCamelIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`LowLine`]\n",
                "* **Case Profile:** [`Mixed`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`LowLine`]: crate::syntax::delimiter::LowLine\n",
                "[`Mixed`]: crate::syntax::profile::Mixed\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(CamelIdent::new("lowerCamel").is_ok());"#, "\n",
                r#"assert!(CamelIdent::new("UpperCamel").is_ok());"#, "\n",
                r#"assert!(CamelIdent::new("lowerCamel_UpperCamel").is_ok());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=CasedCamelChunk,
                fragment=CasedCamelFragment,
                fragment_buf=CasedCamelFragmentBuf,
                ident=CasedCamelIdent,
                module=cased_camel,
                segment=CasedCamelSegment,
            },
            options=Default,
            case=Camel,
            delimiter=LowLine,
            docs=concat!(
                "A camel-cased identifier, which is *either* [`LowerCamelIdent`] ",
                "or [`UpperCamelIdent`] (but not a mix).",
                "\n\n",
                "Camel-cased identifiers are identifiers which usually prefer ",
                "to separate words within a chunk by case convention (lower-to-upper ",
                "or upper-to-lower).",
                "\n\n",
                "If casing alone is not enough to separate words, then an explicit ",
                "delimiter (`_`) may be used.",
                "\n\n",
                "Use this type when you know it's either lowerCamel or UpperCamel, ",
                "but you aren't certain which.",
                "\n\n",
                "[`LowerCamelIdent`]: super::LowerCamelIdent\n",
                "[`UpperCamelIdent`]: super::UpperCamelIdent\n",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "* [`CamelIdent`] *(Less Restrictive)* \n",
                "* `CasedCamelIdent` *(This Identifier)* \n",
                "* [`LowerCamelIdent`] *(More Restrictive)* \n",
                "* [`UpperCamelIdent`] *(More Restrictive)* \n",
                "\n\n",
                "If you need something more general that may match this or ",
                "several other formats, you could consider the [`HybridIdent`] ",
                "identifier formats.",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`CamelIdent`]: super::CamelIdent\n",
                "[`LowerCamelIdent`]: super::LowerCamelIdent\n",
                "[`UpperCamelIdent`]: super::UpperCamelIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`LowLine`]\n",
                "* **Case Profile:** [`Camel`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`LowLine`]: crate::syntax::delimiter::LowLine\n",
                "[`Camel`]: crate::syntax::profile::Camel\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(CasedCamelIdent::new("lowerCamel").is_ok());"#, "\n",
                r#"assert!(CasedCamelIdent::new("UpperCamel").is_ok());"#, "\n",
                r#"assert!(CasedCamelIdent::new("lowerCamel_UpperCamel").is_err());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=LowerCamelChunk,
                fragment=LowerCamelFragment,
                fragment_buf=LowerCamelFragmentBuf,
                ident=LowerCamelIdent,
                module=lower_camel,
                segment=LowerCamelSegment,
            },
            options=Default,
            case=LowerCamel,
            delimiter=LowLine,
            docs=concat!(
                "A camel-cased identifier, whose first character of each chunk ",
                "is either lowercase, or uncased.",
                "\n\n",
                "Camel-cased identifiers are identifiers which usually prefer ",
                "to separate words within a chunk by case convention (lower-to-upper ",
                "or upper-to-lower).",
                "\n\n",
                "If casing alone is not enough to separate words, then an explicit ",
                "delimiter (`_`) may be used.",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "Within the same format of identifiers (camel-cased), this is one ",
                "of the most restrictive forms. However, there are other ",
                "less-restrictive forms.",
                "\n\n",
                "* [`CamelIdent`] *(Less Restrictive)* \n",
                "* [`CasedCamelIdent`] *(Less Restrictive)* \n",
                "* `LowerCamelIdent` *(This Identifier)* \n",
                "* [`UpperCamelIdent`] *(Different Restrictions)* \n",
                "\n\n",
                "If you need something more general that may match this or ",
                "several other formats, you could consider the [`HybridIdent`] ",
                "identifier formats.",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`CamelIdent`]: super::CamelIdent\n",
                "[`CasedCamelIdent`]: super::CasedCamelIdent\n",
                "[`UpperCamelIdent`]: super::UpperCamelIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`LowLine`]\n",
                "* **Case Profile:** [`LowerCamel`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`LowLine`]: crate::syntax::delimiter::LowLine\n",
                "[`LowerCamel`]: crate::syntax::profile::LowerCamel\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(LowerCamelIdent::new("lowerCamel").is_ok());"#, "\n",
                r#"assert!(LowerCamelIdent::new("UpperCamel").is_err());"#, "\n",
                r#"assert!(LowerCamelIdent::new("lowerCamel_UpperCamel").is_err());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=UpperCamelChunk,
                fragment=UpperCamelFragment,
                fragment_buf=UpperCamelFragmentBuf,
                ident=UpperCamelIdent,
                module=upper_camel,
                segment=UpperCamelSegment,
            },
            options=Default,
            case=UpperCamel,
            delimiter=LowLine,
            docs=concat!(
                "A camel-cased identifier, whose first character of each chunk ",
                "is either uppercase, uncased, or titlecase.",
                "\n\n",
                "Camel-cased identifiers are identifiers which usually prefer ",
                "to separate words within a chunk by case convention (lower-to-upper ",
                "or upper-to-lower).",
                "\n\n",
                "If casing alone is not enough to separate words, then an explicit ",
                "delimiter (`_`) may be used.",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "Within the same format of identifiers (camel-cased), this is one ",
                "of the most restrictive forms. However, there are other ",
                "less-restrictive forms.",
                "\n\n",
                "* [`CamelIdent`] *(Less Restrictive)* \n",
                "* [`CasedCamelIdent`] *(Less Restrictive)* \n",
                "* [`LowerCamelIdent`] *(Different Restrictions)* \n",
                "* `UpperCamelIdent` *(This Identifier)* \n",
                "\n\n",
                "If you need something more general that may match this or ",
                "several other formats, you could consider the [`HybridIdent`] ",
                "identifier formats.",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`CamelIdent`]: super::CamelIdent\n",
                "[`CasedCamelIdent`]: super::CasedCamelIdent\n",
                "[`LowerCamelIdent`]: super::LowerCamelIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`LowLine`]\n",
                "* **Case Profile:** [`UpperCamel`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`LowLine`]: crate::syntax::delimiter::LowLine\n",
                "[`UpperCamel`]: crate::syntax::profile::UpperCamel\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(UpperCamelIdent::new("lowerCamel").is_err());"#, "\n",
                r#"assert!(UpperCamelIdent::new("UpperCamel").is_ok());"#, "\n",
                r#"assert!(UpperCamelIdent::new("lowerCamel_UpperCamel").is_err());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=HybridChunk,
                fragment=HybridFragment,
                fragment_buf=HybridFragmentBuf,
                ident=HybridIdent,
                module=hybrid,
                segment=HybridSegment,
            },
            options=Default,
            case=Mixed,
            delimiter=AsciiFlatLine,
            docs=concat!(
                "A hybrid-cased identifier, but without specific requirements ",
                "on the casing.",
                "\n\n",
                "Hybrid-cased identifiers are identifiers which usually prefer ",
                "to separate words within a chunk by case convention (lower-to-upper ",
                "or upper-to-lower).",
                "\n\n",
                "If casing alone is not enough to separate words, then an explicit ",
                "delimiter (either `-` or `_`) may be used.",
                "\n\n",
                "Use this type when you want to be as permissive as possible, ",
                "while still allowing for detection of something vaguely hybrid-cased.",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "Within the same format of identifiers (hybrid-cased), this is the ",
                "most permissive form. However, there are more restrictive forms.",
                "\n\n",
                "* `HybridIdent` *(This Identifier)* \n",
                "* [`CasedHybridIdent`] *(More Restrictive)* \n",
                "* [`LowerHybridIdent`] *(More Restrictive)* \n",
                "* [`UpperHybridIdent`] *(More Restrictive)* \n",
                "\n\n",
                "It tends to be the case that hybrid-cased identifiers are the ",
                "most general - and can often satisfy all of the other formats ",
                "(camelCase, snake_case, and kebab-case could all be considered ",
                "more-restricted instances of hybrid case).",
                "\n\n",
                "[`CasedHybridIdent`]: super::CasedHybridIdent\n",
                "[`LowerHybridIdent`]: super::LowerHybridIdent\n",
                "[`UpperHybridIdent`]: super::UpperHybridIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`AsciiFlatLine`]\n",
                "* **Case Profile:** [`Mixed`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`AsciiFlatLine`]: crate::syntax::delimiter::AsciiFlatLine\n",
                "[`Mixed`]: crate::syntax::profile::Mixed\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(HybridIdent::new("-lowerHybrid").is_ok());"#, "\n",
                r#"assert!(HybridIdent::new("-UpperHybrid").is_ok());"#, "\n",
                r#"assert!(HybridIdent::new("-lowerHybrid_UpperHybrid").is_ok());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=CasedHybridChunk,
                fragment=CasedHybridFragment,
                fragment_buf=CasedHybridFragmentBuf,
                ident=CasedHybridIdent,
                module=cased_hybrid,
                segment=CasedHybridSegment,
            },
            options=Default,
            case=Camel,
            delimiter=AsciiFlatLine,
            docs=concat!(
                "A hybrid-cased identifier, which is *either* [`LowerHybridIdent`] ",
                "or [`UpperHybridIdent`] (but not a mix).",
                "\n\n",
                "Hybrid-cased identifiers are identifiers which usually prefer ",
                "to separate words within a chunk by case convention (lower-to-upper ",
                "or upper-to-lower).",
                "\n\n",
                "If casing alone is not enough to separate words, then an explicit ",
                "delimiter (either `-` or `_`) may be used.",
                "\n\n",
                "Use this type when you know it's either lowerHybrid or UpperHybrid, ",
                "but you aren't certain which.",
                "\n\n",
                "[`LowerHybridIdent`]: super::LowerHybridIdent\n",
                "[`UpperHybridIdent`]: super::UpperHybridIdent\n",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "* [`HybridIdent`] *(Less Restrictive)* \n",
                "* `CasedHybridIdent` *(This Identifier)* \n",
                "* [`LowerHybridIdent`] *(More Restrictive)* \n",
                "* [`UpperHybridIdent`] *(More Restrictive)* \n",
                "\n\n",
                "It tends to be the case that hybrid-cased identifiers are the ",
                "most general - and can often satisfy all of the other formats ",
                "(camelCase, snake_case, and kebab-case could all be considered ",
                "more-restricted instances of hybrid case).",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`LowerHybridIdent`]: super::LowerHybridIdent\n",
                "[`UpperHybridIdent`]: super::UpperHybridIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`AsciiFlatLine`]\n",
                "* **Case Profile:** [`Camel`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`AsciiFlatLine`]: crate::syntax::delimiter::AsciiFlatLine\n",
                "[`Camel`]: crate::syntax::profile::Camel\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(CasedHybridIdent::new("-lowerHybrid").is_ok());"#, "\n",
                r#"assert!(CasedHybridIdent::new("-UpperHybrid").is_ok());"#, "\n",
                r#"assert!(CasedHybridIdent::new("-lowerHybrid_UpperHybrid").is_err());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=LowerHybridChunk,
                fragment=LowerHybridFragment,
                fragment_buf=LowerHybridFragmentBuf,
                ident=LowerHybridIdent,
                module=lower_hybrid,
                segment=LowerHybridSegment,
            },
            options=Default,
            case=LowerCamel,
            delimiter=AsciiFlatLine,
            docs=concat!(
                "A hybrid-cased identifier, whose first character of each chunk ",
                "is either lowercase, or uncased.",
                "\n\n",
                "Hybrid-cased identifiers are identifiers which usually prefer ",
                "to separate words within a chunk by case convention (lower-to-upper ",
                "or upper-to-lower).",
                "\n\n",
                "If casing alone is not enough to separate words, then an explicit ",
                "delimiter (either `-` or `_`) may be used.",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "Within the same format of identifiers (hybrid-cased), this is one ",
                "of the most restrictive forms. However, there are other ",
                "less-restrictive forms.",
                "\n\n",
                "* [`HybridIdent`] *(Less Restrictive)* \n",
                "* [`CasedHybridIdent`] *(Less Restrictive)* \n",
                "* `LowerHybridIdent` *(This Identifier)* \n",
                "* [`UpperHybridIdent`] *(Different Restrictions)* \n",
                "\n\n",
                "It tends to be the case that hybrid-cased identifiers are the ",
                "most general - and can often satisfy all of the other formats ",
                "(camelCase, snake_case, and kebab-case could all be considered ",
                "more-restricted instances of hybrid case).",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`CasedHybridIdent`]: super::CasedHybridIdent\n",
                "[`UpperHybridIdent`]: super::UpperHybridIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`AsciiFlatLine`]\n",
                "* **Case Profile:** [`LowerCamel`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`AsciiFlatLine`]: crate::syntax::delimiter::AsciiFlatLine\n",
                "[`LowerCamel`]: crate::syntax::profile::LowerCamel\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(LowerHybridIdent::new("-lowerHybrid").is_ok());"#, "\n",
                r#"assert!(LowerHybridIdent::new("-UpperHybrid").is_err());"#, "\n",
                r#"assert!(LowerHybridIdent::new("-lowerHybrid_UpperHybrid").is_err());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=UpperHybridChunk,
                fragment=UpperHybridFragment,
                fragment_buf=UpperHybridFragmentBuf,
                ident=UpperHybridIdent,
                module=upper_hybrid,
                segment=UpperHybridSegment,
            },
            options=Default,
            case=UpperCamel,
            delimiter=AsciiFlatLine,
            docs=concat!(
                "A hybrid-cased identifier, whose first character of each chunk ",
                "is either uppercase, uncased, or titlecase.",
                "\n\n",
                "Hybrid-cased identifiers are identifiers which usually prefer ",
                "to separate words within a chunk by case convention (lower-to-upper ",
                "or upper-to-lower).",
                "\n\n",
                "If casing alone is not enough to separate words, then an explicit ",
                "delimiter (either `-` or `_`) may be used.",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "Within the same format of identifiers (hybrid-cased), this is one ",
                "of the most restrictive forms. However, there are other ",
                "less-restrictive forms.",
                "\n\n",
                "* [`HybridIdent`] *(Less Restrictive)* \n",
                "* [`CasedHybridIdent`] *(Less Restrictive)* \n",
                "* [`LowerHybridIdent`] *(Different Restrictions)* \n",
                "* `UpperHybridIdent` *(This Identifier)* \n",
                "\n\n",
                "It tends to be the case that hybrid-cased identifiers are the ",
                "most general - and can often satisfy all of the other formats ",
                "(camelCase, snake_case, and kebab-case could all be considered ",
                "more-restricted instances of hybrid case).",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`CasedHybridIdent`]: super::CasedHybridIdent\n",
                "[`LowerHybridIdent`]: super::LowerHybridIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`AsciiFlatLine`]\n",
                "* **Case Profile:** [`UpperCamel`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`AsciiFlatLine`]: crate::syntax::delimiter::AsciiFlatLine\n",
                "[`UpperCamel`]: crate::syntax::profile::UpperCamel\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(UpperHybridIdent::new("-lowerHybrid").is_err());"#, "\n",
                r#"assert!(UpperHybridIdent::new("-UpperHybrid").is_ok());"#, "\n",
                r#"assert!(UpperHybridIdent::new("-lowerHybrid_UpperHybrid").is_err());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=KebabChunk,
                fragment=KebabFragment,
                fragment_buf=KebabFragmentBuf,
                ident=KebabIdent,
                module=kebab,
                segment=KebabSegment,
            },
            options=NoBoundaries,
            case=Mixed,
            delimiter=HyphenMinus,
            docs=concat!(
                "A kebab-cased identifier, but without specific requirements ",
                "on the casing.",
                "\n\n",
                "Kebab-cased identifiers are identifiers which usually have ",
                "a uniform casing (either lower or upper), and as such do not ",
                "separate words by case convention.",
                "\n\n",
                "If words should be separated, it must be done using an explicit ",
                "delimiter (`-`).",
                "\n\n",
                "Use this type when you want to be as permissive as possible, ",
                "while still allowing for detection of something vaguely kebab-cased.",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "Within the same format of identifiers (kebab-cased), this is the ",
                "most permissive form. However, there are more restrictive forms.",
                "\n\n",
                "* `KebabIdent` *(This Identifier)* \n",
                "* [`CasedKebabIdent`] *(More Restrictive)* \n",
                "* [`LowerKebabIdent`] *(More Restrictive)* \n",
                "* [`UpperKebabIdent`] *(More Restrictive)* \n",
                "\n\n",
                "If you need something more general that may match this or ",
                "several other formats, you could consider the [`HybridIdent`] ",
                "identifier formats.",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`CasedKebabIdent`]: super::CasedKebabIdent\n",
                "[`LowerKebabIdent`]: super::LowerKebabIdent\n",
                "[`UpperKebabIdent`]: super::UpperKebabIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`HyphenMinus`]\n",
                "* **Case Profile:** [`Mixed`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`HyphenMinus`]: crate::syntax::delimiter::HyphenMinus\n",
                "[`Mixed`]: crate::syntax::profile::Mixed\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(KebabIdent::new("lower-kebab").is_ok());"#, "\n",
                r#"assert!(KebabIdent::new("UPPER-KEBAB").is_ok());"#, "\n",
                r#"assert!(KebabIdent::new("Mixed-Kebab").is_ok());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=CasedKebabChunk,
                fragment=CasedKebabFragment,
                fragment_buf=CasedKebabFragmentBuf,
                ident=CasedKebabIdent,
                module=cased_kebab,
                segment=CasedKebabSegment,
            },
            options=NoBoundaries,
            case=Uniform,
            delimiter=HyphenMinus,
            docs=concat!(
                "A kebab-cased identifier, which is *either* [`LowerKebabIdent`] ",
                "or [`UpperKebabIdent`] (but not a mix).",
                "\n\n",
                "Kebab-cased identifiers are identifiers which usually have ",
                "a uniform casing (either lower or upper), and as such do not ",
                "separate words by case convention.",
                "\n\n",
                "If words should be separated, it must be done using an explicit ",
                "delimiter (`-`).",
                "\n\n",
                "Use this type when you know it's either lower-kebab or UPPER-KEBAB, ",
                "but you aren't certain which.",
                "\n\n",
                "[`LowerKebabIdent`]: super::LowerKebabIdent\n",
                "[`UpperKebabIdent`]: super::UpperKebabIdent\n",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "* [`KebabIdent`] *(Less Restrictive)* \n",
                "* `CasedKebabIdent` *(This Identifier)* \n",
                "* [`LowerKebabIdent`] *(More Restrictive)* \n",
                "* [`UpperKebabIdent`] *(More Restrictive)* \n",
                "\n\n",
                "If you need something more general that may match this or ",
                "several other formats, you could consider the [`HybridIdent`] ",
                "identifier formats.",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`KebabIdent`]: super::KebabIdent\n",
                "[`LowerKebabIdent`]: super::LowerKebabIdent\n",
                "[`UpperKebabIdent`]: super::UpperKebabIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`HyphenMinus`]\n",
                "* **Case Profile:** [`Uniform`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`HyphenMinus`]: crate::syntax::delimiter::HyphenMinus\n",
                "[`Uniform`]: crate::syntax::profile::Uniform\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(CasedKebabIdent::new("lower-kebab").is_ok());"#, "\n",
                r#"assert!(CasedKebabIdent::new("UPPER-KEBAB").is_ok());"#, "\n",
                r#"assert!(CasedKebabIdent::new("Mixed-Kebab").is_err());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=LowerKebabChunk,
                fragment=LowerKebabFragment,
                fragment_buf=LowerKebabFragmentBuf,
                ident=LowerKebabIdent,
                module=lower_kebab,
                segment=LowerKebabSegment,
            },
            options=NoBoundaries,
            case=Lower,
            delimiter=HyphenMinus,
            docs=concat!(
                "A kebab-cased identifier, where each character is either ",
                "lowercase or uncased.",
                "\n\n",
                "Kebab-cased identifiers are identifiers which usually have ",
                "a uniform casing (either lower or upper), and as such do not ",
                "separate words by case convention.",
                "\n\n",
                "If words should be separated, it must be done using an explicit ",
                "delimiter (`-`).",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "Within the same format of identifiers (kebab-cased), this is one ",
                "of the most restrictive forms. However, there are other ",
                "less-restrictive forms.",
                "\n\n",
                "* [`KebabIdent`] *(Less Restrictive)* \n",
                "* [`CasedKebabIdent`] *(Less Restrictive)* \n",
                "* `LowerKebabIdent` *(This Identifier)* \n",
                "* [`UpperKebabIdent`] *(Different Restrictions)* \n",
                "\n\n",
                "If you need something more general that may match this or ",
                "several other formats, you could consider the [`HybridIdent`] ",
                "identifier formats.",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`KebabIdent`]: super::KebabIdent\n",
                "[`CasedKebabIdent`]: super::CasedKebabIdent\n",
                "[`UpperKebabIdent`]: super::UpperKebabIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`HyphenMinus`]\n",
                "* **Case Profile:** [`Lower`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`HyphenMinus`]: crate::syntax::delimiter::HyphenMinus\n",
                "[`Lower`]: crate::syntax::profile::Lower\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(LowerKebabIdent::new("lower-kebab").is_ok());"#, "\n",
                r#"assert!(LowerKebabIdent::new("UPPER-KEBAB").is_err());"#, "\n",
                r#"assert!(LowerKebabIdent::new("Mixed-Kebab").is_err());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=UpperKebabChunk,
                fragment=UpperKebabFragment,
                fragment_buf=UpperKebabFragmentBuf,
                ident=UpperKebabIdent,
                module=upper_kebab,
                segment=UpperKebabSegment,
            },
            options=NoBoundaries,
            case=Upper,
            delimiter=HyphenMinus,
            docs=concat!(
                "A kebab-cased identifier, where each character is either ",
                "uppercase, uncased, or Greek titlecase.",
                "\n\n",
                "Kebab-cased identifiers are identifiers which usually have ",
                "a uniform casing (either lower or upper), and as such do not ",
                "separate words by case convention.",
                "\n\n",
                "If words should be separated, it must be done using an explicit ",
                "delimiter (`-`).",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "Within the same format of identifiers (kebab-cased), this is one ",
                "of the most restrictive forms. However, there are other ",
                "less-restrictive forms.",
                "\n\n",
                "* [`KebabIdent`] *(Less Restrictive)* \n",
                "* [`CasedKebabIdent`] *(Less Restrictive)* \n",
                "* [`LowerKebabIdent`] *(Different Restrictions)* \n",
                "* `UpperKebabIdent` *(This Identifier)* \n",
                "\n\n",
                "If you need something more general that may match this or ",
                "several other formats, you could consider the [`HybridIdent`] ",
                "identifier formats.",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`KebabIdent`]: super::KebabIdent\n",
                "[`CasedKebabIdent`]: super::CasedKebabIdent\n",
                "[`LowerKebabIdent`]: super::LowerKebabIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`HyphenMinus`]\n",
                "* **Case Profile:** [`Upper`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`HyphenMinus`]: crate::syntax::delimiter::HyphenMinus\n",
                "[`Upper`]: crate::syntax::profile::Upper\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(UpperKebabIdent::new("lower-kebab").is_err());"#, "\n",
                r#"assert!(UpperKebabIdent::new("UPPER-KEBAB").is_ok());"#, "\n",
                r#"assert!(UpperKebabIdent::new("Mixed-Kebab").is_err());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=SnakeChunk,
                fragment=SnakeFragment,
                fragment_buf=SnakeFragmentBuf,
                ident=SnakeIdent,
                module=snake,
                segment=SnakeSegment,
            },
            options=NoBoundaries,
            case=Mixed,
            delimiter=LowLine,
            docs=concat!(
                "A snake-cased identifier, but without specific requirements ",
                "on the casing.",
                "\n\n",
                "Snake-cased identifiers are identifiers which usually have ",
                "a uniform casing (either lower or upper), and as such do not ",
                "separate words by case convention.",
                "\n\n",
                "If words should be separated, it must be done using an explicit ",
                "delimiter (`_`).",
                "\n\n",
                "Use this type when you want to be as permissive as possible, ",
                "while still allowing for detection of something vaguely snake-cased.",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "Within the same format of identifiers (snake-cased), this is the ",
                "most permissive form. However, there are more restrictive forms.",
                "\n\n",
                "* `SnakeIdent` *(This Identifier)* \n",
                "* [`CasedSnakeIdent`] *(More Restrictive)* \n",
                "* [`LowerSnakeIdent`] *(More Restrictive)* \n",
                "* [`UpperSnakeIdent`] *(More Restrictive)* \n",
                "\n\n",
                "If you need something more general that may match this or ",
                "several other formats, you could consider the [`HybridIdent`] ",
                "identifier formats.",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`CasedSnakeIdent`]: super::CasedSnakeIdent\n",
                "[`LowerSnakeIdent`]: super::LowerSnakeIdent\n",
                "[`UpperSnakeIdent`]: super::UpperSnakeIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`LowLine`]\n",
                "* **Case Profile:** [`Mixed`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`LowLine`]: crate::syntax::delimiter::LowLine\n",
                "[`Mixed`]: crate::syntax::profile::Mixed\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(SnakeIdent::new("lower_snake").is_ok());"#, "\n",
                r#"assert!(SnakeIdent::new("UPPER_SNAKE").is_ok());"#, "\n",
                r#"assert!(SnakeIdent::new("Mixed_Snake").is_ok());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=CasedSnakeChunk,
                fragment=CasedSnakeFragment,
                fragment_buf=CasedSnakeFragmentBuf,
                ident=CasedSnakeIdent,
                module=cased_snake,
                segment=CasedSnakeSegment,
            },
            options=NoBoundaries,
            case=Uniform,
            delimiter=LowLine,
            docs=concat!(
                "A snake-cased identifier, which is *either* [`LowerSnakeIdent`] ",
                "or [`UpperSnakeIdent`] (but not a mix).",
                "\n\n",
                "Snake-cased identifiers are identifiers which usually have ",
                "a uniform casing (either lower or upper), and as such do not ",
                "separate words by case convention.",
                "\n\n",
                "If words should be separated, it must be done using an explicit ",
                "delimiter (`_`).",
                "\n\n",
                "Use this type when you know it's either lower-snake or UPPER-SNAKE, ",
                "but you aren't certain which.",
                "\n\n",
                "[`LowerSnakeIdent`]: super::LowerSnakeIdent\n",
                "[`UpperSnakeIdent`]: super::UpperSnakeIdent\n",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "* [`SnakeIdent`] *(Less Restrictive)* \n",
                "* `CasedSnakeIdent` *(This Identifier)* \n",
                "* [`LowerSnakeIdent`] *(More Restrictive)* \n",
                "* [`UpperSnakeIdent`] *(More Restrictive)* \n",
                "\n\n",
                "If you need something more general that may match this or ",
                "several other formats, you could consider the [`HybridIdent`] ",
                "identifier formats.",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`SnakeIdent`]: super::SnakeIdent\n",
                "[`LowerSnakeIdent`]: super::LowerSnakeIdent\n",
                "[`UpperSnakeIdent`]: super::UpperSnakeIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`LowLine`]\n",
                "* **Case Profile:** [`Uniform`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`LowLine`]: crate::syntax::delimiter::LowLine\n",
                "[`Uniform`]: crate::syntax::profile::Uniform\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(CasedSnakeIdent::new("lower_snake").is_ok());"#, "\n",
                r#"assert!(CasedSnakeIdent::new("UPPER_SNAKE").is_ok());"#, "\n",
                r#"assert!(CasedSnakeIdent::new("Mixed_Snake").is_err());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=LowerSnakeChunk,
                fragment=LowerSnakeFragment,
                fragment_buf=LowerSnakeFragmentBuf,
                ident=LowerSnakeIdent,
                module=lower_snake,
                segment=LowerSnakeSegment,
            },
            options=NoBoundaries,
            case=Lower,
            delimiter=LowLine,
            docs=concat!(
                "A snake-cased identifier, where each character is either ",
                "lowercase or uncased.",
                "\n\n",
                "Snake-cased identifiers are identifiers which usually have ",
                "a uniform casing (either lower or upper), and as such do not ",
                "separate words by case convention.",
                "\n\n",
                "If words should be separated, it must be done using an explicit ",
                "delimiter (`_`).",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "Within the same format of identifiers (snake-cased), this is one ",
                "of the most restrictive forms. However, there are other ",
                "less-restrictive forms.",
                "\n\n",
                "* [`SnakeIdent`] *(Less Restrictive)* \n",
                "* [`CasedSnakeIdent`] *(Less Restrictive)* \n",
                "* `LowerSnakeIdent` *(This Identifier)* \n",
                "* [`UpperSnakeIdent`] *(Different Restrictions)* \n",
                "\n\n",
                "If you need something more general that may match this or ",
                "several other formats, you could consider the [`HybridIdent`] ",
                "identifier formats.",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`SnakeIdent`]: super::SnakeIdent\n",
                "[`CasedSnakeIdent`]: super::CasedSnakeIdent\n",
                "[`UpperSnakeIdent`]: super::UpperSnakeIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`LowLine`]\n",
                "* **Case Profile:** [`Lower`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`LowLine`]: crate::syntax::delimiter::LowLine\n",
                "[`Lower`]: crate::syntax::profile::Lower\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(LowerSnakeIdent::new("lower_snake").is_ok());"#, "\n",
                r#"assert!(LowerSnakeIdent::new("UPPER_SNAKE").is_err());"#, "\n",
                r#"assert!(LowerSnakeIdent::new("Mixed_Snake").is_err());"#, "\n",
                "```\n",
            ),
        }
        impl_type_aliases! {
            $($tt)*
            names={
                chunk=UpperSnakeChunk,
                fragment=UpperSnakeFragment,
                fragment_buf=UpperSnakeFragmentBuf,
                ident=UpperSnakeIdent,
                module=upper_snake,
                segment=UpperSnakeSegment,
            },
            options=NoBoundaries,
            case=Upper,
            delimiter=LowLine,
            docs=concat!(
                "A snake-cased identifier, where each character is either ",
                "uppercase, uncased, or Greek titlecase.",
                "\n\n",
                "Snake-cased identifiers are identifiers which usually have ",
                "a uniform casing (either lower or upper), and as such do not ",
                "separate words by case convention.",
                "\n\n",
                "If words should be separated, it must be done using an explicit ",
                "delimiter (`_`).",
                "\n\n",
                "# Related Formats",
                "\n\n",
                "Within the same format of identifiers (snake-cased), this is one ",
                "of the most restrictive forms. However, there are other ",
                "less-restrictive forms.",
                "\n\n",
                "* [`SnakeIdent`] *(Less Restrictive)* \n",
                "* [`CasedSnakeIdent`] *(Less Restrictive)* \n",
                "* [`LowerSnakeIdent`] *(Different Restrictions)* \n",
                "* `UpperSnakeIdent` *(This Identifier)* \n",
                "\n\n",
                "If you need something more general that may match this or ",
                "several other formats, you could consider the [`HybridIdent`] ",
                "identifier formats.",
                "\n\n",
                "[`HybridIdent`]: super::HybridIdent\n",
                "[`SnakeIdent`]: super::SnakeIdent\n",
                "[`CasedSnakeIdent`]: super::CasedSnakeIdent\n",
                "[`LowerSnakeIdent`]: super::LowerSnakeIdent\n",
                "\n\n",
                "# Fixed Configuration",
                "\n\n",
                "Regardless of the configuration that you select, the following ",
                "syntax rules will be fixed on this kind of identifier.",
                "\n\n",
                "* **Delimiter:** [`LowLine`]\n",
                "* **Case Profile:** [`Upper`]\n",
                "* **Char Profile:** (Depends on your selection)\n",
                "\n\n",
                "[`LowLine`]: crate::syntax::delimiter::LowLine\n",
                "[`Upper`]: crate::syntax::profile::Upper\n",
                "\n\n",
                "# Examples",
                "\n\n",
                "Basic Usage:",
                "\n\n",
                "```\n",
                "# use typed_ident::presets::ascii::*;\n",
                r#"assert!(UpperSnakeIdent::new("lower_snake").is_err());"#, "\n",
                r#"assert!(UpperSnakeIdent::new("UPPER_SNAKE").is_ok());"#, "\n",
                r#"assert!(UpperSnakeIdent::new("Mixed_Snake").is_err());"#, "\n",
                "```\n",
            ),
        }
    };
}

// =============================================================================
// PRESETS
// =============================================================================

// -----------------------------------------------------------------------------
#[cfg(feature = "unicode")]
#[allow(missing_docs)]
pub mod generic {
    //! Identifiers which are generic across their boundary and character
    //! profile selection, but fixed for delimiter and case profiles.
    //!
    //! See the [`presets`] module documentation for more details.
    //!
    //! [`presets`]: crate::presets
    //!
    #![doc = include_str!("README.md")]

    impl_type_aliases! {}
}

// =============================================================================
// PROFILE PRESETS
// =============================================================================

// -----------------------------------------------------------------------------
#[allow(missing_docs)]
pub mod ascii {
    //! Identifiers using the [`Ascii`] character profile.
    //!
    //! See the [`presets`] module documentation for more details.
    //!
    //! [`Ascii`]: crate::syntax::profile::Ascii
    //! [`presets`]: crate::presets
    //!
    #![doc = include_str!("README.md")]

    impl_type_aliases! {
        profile=Ascii,
    }
}

// -----------------------------------------------------------------------------
#[cfg(feature = "unicode")]
#[allow(missing_docs)]
pub mod strict {
    //! Identifiers using the [`Strict`] character profile.
    //!
    //! See the [`presets`] module documentation for more details.
    //!
    //! [`Strict`]: crate::syntax::profile::Strict
    //! [`presets`]: crate::presets
    //!
    #![doc = include_str!("README.md")]

    impl_type_aliases! {
        profile=Strict,
    }
}

// -----------------------------------------------------------------------------
#[cfg(feature = "unicode")]
#[allow(missing_docs)]
pub mod unicode {
    //! Identifiers using the [`Unicode`] character profile.
    //!
    //! See the [`presets`] module documentation for more details.
    //!
    //! [`Unicode`]: crate::syntax::profile::Unicode
    //! [`presets`]: crate::presets
    //!
    #![doc = include_str!("README.md")]

    impl_type_aliases! {
        profile=Unicode,
    }
}
